name: HSCPathways
channels:
  - conda-forge
  - bryanwweber
dependencies:
  - python=3.4
  - bryanwweber::coolprop
  - conda-forge::jupyter
  - pandas
  - descartes
  - xlsxwriter
  - pillow
  - xlrd
  - openpyxl
  - pip
  - matplotlib=1.5.1
  - pip:
    - .\.